### Creating a tensor

In [4]:
import torch

# Create tensor row
tensor_row = torch.tensor([1, 2, 3])

# Create tensor column
tensor_column = torch.tensor(
    [
        [1],
        [2],
        [3]
    ]
)

### Creating a Tensor from a NumPy Array

In [8]:
import numpy as np
import torch

# Create a NumPy array
vector_row = np.array([1, 2, 3])

# Convert the NumPy array to a tensor
tensor_row = torch.tensor(vector_row.tolist())

### Creating a sparse tensor

In [10]:
import torch

# Create a regular tensor
tensor = torch.tensor(
    [
        [0, 0],
        [0, 1],
        [3, 0]
    ]
)

# Convert the regular tensor to a sparse tensor
sparse_tensor = tensor.to_sparse()

print(type(tensor))
print(type(sparse_tensor))

<class 'torch.Tensor'>
<class 'torch.Tensor'>


### Selecting tensor elements

In [13]:
import torch

# Create a vector tensor
vector = torch.tensor([1, 2, 3, 4, 5, 6])

# Create a matrix tensor
matrix = torch.tensor(
[
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
)

# Print the third element of the vector
print(vector[2])

# Print the element in the second row and second column
print(matrix[1, 1])

tensor(3)
tensor(5)


In [14]:
# Output all elements of the vector
print(vector[:])

# Output all elements of the vector up to the third element (inclusive)
print(vector[:3])

# Output all elements of the vector after the third element
print(vector[3:])

# Output the last element of the vector
print(vector[-1])

# Output the elements of the first two rows and all columns of the matrix
print(matrix[:2, :])

# Output the elements of all rows and the second column
print(matrix[:, 1:2])


tensor([1, 2, 3, 4, 5, 6])
tensor([1, 2, 3])
tensor([4, 5, 6])
tensor(6)
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[2],
        [5],
        [8]])


In [16]:
# Reverse the vector using slicing ERROR
# vector[::-1]

vector.flip(dims=(-1,))


tensor([6, 5, 4, 3, 2, 1])

### Description of the tensor

In [20]:
import torch

# Create a tensor
tensor = torch.tensor([[1, 2, 3], [1, 2, 3]])

# Shape of the tensor
print(tensor.shape)

# Data type of the tensor
print(tensor.dtype)

# Memory layout of the tensor
print(tensor.layout)

# Device on which the tensor is stored
print(tensor.device)

torch.Size([2, 3])
torch.int64
torch.strided
cpu


### Operations on elements

In [21]:
import torch

# Create a tensor
tensor = torch.tensor([1, 2, 3])

# Broadcast an arithmetic operation to all elements of the tensor
print(tensor * 100)

tensor([100, 200, 300])


### Finding the largest and smallest values

In [23]:
import torch

# Create a tensor
tensor = torch.tensor([1, 2, 3])

# Find the maximum value
print(tensor.max())

# Find the minimum value
print(tensor.min())

tensor(3)
tensor(1)


### Changing the shape of tensors

In [25]:
import torch

# Create a tensor of shape 4x3
tensor = torch.tensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9],
                       [10, 11, 12]])

# Change the shape of the tensor to 2x6
tensor.reshape(2, 6)

tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])

### Transpose of a tensor

In [26]:
import torch

# Create a two-dimensional tensor
tensor = torch.tensor([[1, 2, 3]])

# Transpose it
print(tensor.T)

tensor([[1],
        [2],
        [3]])


### Transformation into a one-dimensional tensor

In [29]:
import torch

# Create tensor
tensor = torch.tensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])
# Flatten tensor
tensor.flatten()

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

### Calculating the scalar product

In [ ]:
import torch

# Create a one-dimensional tensor
tensor_1 = torch.tensor([1, 2, 3])

# Create another one-dimensional tensor
tensor_2 = torch.tensor([4, 5, 6])

# Calculate scalar multiplication of two tensors
tensor_1.dot(tensor_2)

tensor(32)

### Tensor multiplication

In [31]:
import torch

# Create a one-dimensional tensor
tensor_1 = torch.tensor([1, 2, 3])

# Create another one-dimensional tensor
tensor_2 = torch.tensor([4, 5, 6])

# Multiply two tensors element-wise
tensor_1 * tensor_2

tensor([ 4, 10, 18])

In [32]:
# Addiction of two tensors
print(tensor_1 + tensor_2)

# Subtraction of two tensors
print(tensor_1 - tensor_2)

# Division of two tensors
print(tensor_1 / tensor_2)


tensor([5, 7, 9])
tensor([-3, -3, -3])
tensor([0.2500, 0.4000, 0.5000])
