### Load library

In [1]:
import numpy as np

### Create Vector

In [2]:
vector_row = np.array([1, 2, 3, 4, 5])
print("Row Vector:\n", vector_row)
print("Slice vector:", vector_row[2:])
vector_column = np.array([[1], [2], [3], [4], [5]])
print("Column Vector:\n", vector_column)

Row Vector:
 [1 2 3 4 5]
Slice vector: [3 4 5]
Column Vector:
 [[1]
 [2]
 [3]
 [4]
 [5]]


### Create Matrix

In [3]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Matrix:\n", matrix)
print("Matrix Element:", matrix[1, 1])
print("Matrix Row 2:", matrix[1, :])
print("Matrix Column 2:", matrix[:, 1])

Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix Element: 5
Matrix Row 2: [4 5 6]
Matrix Column 2: [2 5 8]


### Sparse matrix

In [4]:
from scipy import sparse
matrix = np.array([
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
    [3, 0, 0, 0, 0, 0, 0, 0, 0, 0],]
)
print("Original Matrix:\n", matrix)
matrix_sparse = sparse.csr_matrix(matrix)
print("Sparse Matrix:\n", matrix_sparse)

Original Matrix:
 [[0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [3 0 0 0 0 0 0 0 0 0]]
Sparse Matrix:
 <Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (3, 10)>
  Coords	Values
  (1, 1)	1
  (2, 0)	3


### Matrix Shape

In [5]:
matrix_zero = np.zeros(shape=(3, 3))
print("Zero Matrix:\n", matrix_zero)

Zero Matrix:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
matrix_one = np.full(shape=(4, 4), fill_value=1)
print("One Matrix:\n", matrix_one)

One Matrix:
 [[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


### Get Shape, Size, Ndim

In [7]:
matrix = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])
print("Matrix shape:\n", matrix.shape)
print("Matrix size:\n", matrix.size)
print("Matrix dimensions:\n", matrix.ndim)

Matrix shape:
 (3, 4)
Matrix size:
 12
Matrix dimensions:
 2


### Lambda function

In [8]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
add_100 = lambda i: i + 100
matrix_plus_100 = add_100(matrix)
print("Matrix plus 100:\n", matrix_plus_100)
matrix = matrix + 100
print("Matrix plus 100 different approach:\n", matrix)
print("Matrix min:\n", matrix.min())
print("Matrix max:\n", matrix.max())
print("Matrix max in every column:\n", matrix.max(axis=0))
print("Matrix max in every row:\n", matrix.max(axis=1))


Matrix plus 100:
 [[101 102 103]
 [104 105 106]
 [107 108 109]]
Matrix plus 100 different approach:
 [[101 102 103]
 [104 105 106]
 [107 108 109]]
Matrix min:
 101
Matrix max:
 109
Matrix max in every column:
 [107 108 109]
Matrix max in every row:
 [103 106 109]


### Mean, var, std

In [9]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Mean:\n", matrix.mean())
print("Var:\n", matrix.var())
print("Std:\n", matrix.std())


Mean:
 5.0
Var:
 6.666666666666667
Std:
 2.581988897471611


### Reshape matrix

In [10]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])
matrix.reshape(2, 6)
print("Reshaped Matrix:\n", matrix.reshape(2, 6))

Reshaped Matrix:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


### Transpose of a vector or matrix

In [11]:
matrix = np.array([
    [1, 2, 3], 
    [4, 5, 6],
    [7, 8, 9]
])
print("Matrix Transpose:\n", matrix.T)
vector = np.array([[1, 2, 3, 4, 5, 6, 7, 8]])
print("Vector Shape:\n", vector.shape)
print("Vector Transpose:\n", vector.T)
print("Vector Transpose Shape:\n", vector.T.shape)

Matrix Transpose:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
Vector Shape:
 (1, 8)
Vector Transpose:
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
Vector Transpose Shape:
 (8, 1)


### Flatten matrix

In [12]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Matrix flatten:\n", matrix.flatten())
print("Matrix flatten alternate:\n", matrix.reshape(1, -1))

Matrix flatten:
 [1 2 3 4 5 6 7 8 9]
Matrix flatten alternate:
 [[1 2 3 4 5 6 7 8 9]]


### Ravel matrix

In [13]:
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])
matrix_list = [matrix_a, matrix_b]
print("Matrix ravel:\n", np.ravel(matrix_list))

Matrix ravel:
 [1 2 3 4 5 6 7 8]


### Rank of matrix

In [14]:
matrix = np.array([
    [1, 1, 1],
    [1, 1, 10],
    [1, 1, 15]])
print("Matrix rank:\n", np.linalg.matrix_rank(matrix))
print("Matrix diagonal:\n", matrix.diagonal())
print("Matrix diagonal offset 1:\n", matrix.diagonal(offset=1))
print("Matrix diagonal offset -1:\n", matrix.diagonal(offset=-1))
print("Matrix trace:\n", matrix.trace())

Matrix rank:
 2
Matrix diagonal:
 [ 1  1 15]
Matrix diagonal offset 1:
 [ 1 10]
Matrix diagonal offset -1:
 [1 1]
Matrix trace:
 17


### Scalar multiplication

In [15]:
vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])
print("Dot Product:\n", np.dot(vector_a, vector_b))

Dot Product:
 32


### Add, subtract,multiply, divide

In [16]:
matrix_a = np.array([[1, 1, 1], [1, 1, 1], [1, 1, 2]])
matrix_b = np.array([[1, 3, 1], [1, 3, 1], [1, 3, 8]])
print("Matrix add:\n", np.add(matrix_a, matrix_b))
print("Matrix subtract:\n", np.subtract(matrix_a, matrix_b))
print("Matrix multiply:\n", np.multiply(matrix_a, matrix_b))
print("Matrix divide:\n", np.divide(matrix_a, matrix_b))


Matrix add:
 [[ 2  4  2]
 [ 2  4  2]
 [ 2  4 10]]
Matrix subtract:
 [[ 0 -2  0]
 [ 0 -2  0]
 [ 0 -2 -6]]
Matrix multiply:
 [[ 1  3  1]
 [ 1  3  1]
 [ 1  3 16]]
Matrix divide:
 [[1.         0.33333333 1.        ]
 [1.         0.33333333 1.        ]
 [1.         0.33333333 0.25      ]]


### Inverted matrix

In [17]:
matrix = np.array([[1, 4], [2, 5]])
print("Matrix inverted:\n", np.linalg.inv(matrix))

Matrix inverted:
 [[-1.66666667  1.33333333]
 [ 0.66666667 -0.33333333]]


### Generate pseudo random matrix

In [18]:
np.random.seed(0)
matrix = np.random.rand(3, 3)
print("Random Matrix:\n", matrix)
matrix_int = np.random.randint(0, 100, size=(3, 3))
print("Random Integer Matrix:\n", matrix_int)
matrix_normal = np.random.normal(loc=0.0, scale=1.0, size=(3, 3))
print("Random Normal Matrix:\n", matrix_normal)

Random Matrix:
 [[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]
 [0.43758721 0.891773   0.96366276]]
Random Integer Matrix:
 [[58 65 39]
 [87 46 88]
 [81 37 25]]
Random Normal Matrix:
 [[ 0.44386323  0.33367433  1.49407907]
 [-0.20515826  0.3130677  -0.85409574]
 [-2.55298982  0.6536186   0.8644362 ]]
