### Feature scaling

In [24]:
import numpy as np
from sklearn import preprocessing

In [25]:
# Creating the feature array
feature = np.array([[-500.5], [-100.1], [0], [100.1], [900.9]])
# Creating the Scaler object
minmax_scale = preprocessing.MinMaxScaler(feature_range=(0, 1))
# Scaling the feature
scaled_feature = minmax_scale.fit_transform(feature)
print(scaled_feature)

[[0.        ]
 [0.28571429]
 [0.35714286]
 [0.42857143]
 [1.        ]]


### Standardization of the feature

In [26]:
x = np.array([
    [-1000.1],
    [-200.2],
    [500.5],
    [600.6],
    [9000.9]])
# Creating the Scaler object
scaler = preprocessing.StandardScaler()
# Transform a feature
standardized = scaler.fit_transform(x)
print(standardized)
print("Mean: ", round(standardized.mean()))
print("Standard deviation:", standardized.std())

# scaling of a feature using the median and quantile range.
robust_scaler = preprocessing.RobustScaler()
robust = robust_scaler.fit_transform(x)
print(robust)

[[-0.76058269]
 [-0.54177196]
 [-0.35009716]
 [-0.32271504]
 [ 1.97516685]]
Mean:  0
Standard deviation: 1.0
[[-1.87387612]
 [-0.875     ]
 [ 0.        ]
 [ 0.125     ]
 [10.61488511]]


### Normalization of observed data

In [27]:
from sklearn.preprocessing import Normalizer

features = np.array([
    [0.5, 0.5],
    [1.1, 3.4],
    [1.5, 20.2],
    [1.63, 34.4],
    [10.9, 3.3]])

normalizer_l2 = Normalizer(norm="l2")
features_l2_norm = normalizer_l2.transform(features)
print(features_l2_norm)

[[0.70710678 0.70710678]
 [0.30782029 0.95144452]
 [0.07405353 0.99725427]
 [0.04733062 0.99887928]
 [0.95709822 0.28976368]]


In [28]:
normalizer_l1 = Normalizer(norm="l1")
features_l1_norm = normalizer_l1.transform(features)
print(features_l1_norm)

[[0.5        0.5       ]
 [0.24444444 0.75555556]
 [0.06912442 0.93087558]
 [0.04524008 0.95475992]
 [0.76760563 0.23239437]]


### Generating polynomial and interacting features

In [29]:
from sklearn.preprocessing import PolynomialFeatures

features = np.array([[2, 3], [2, 3], [2, 3]])
polynomial_interaction = PolynomialFeatures(degree=2, include_bias=False)
features_polynomial = polynomial_interaction.fit_transform(features)
print(features_polynomial)

[[2. 3. 4. 6. 9.]
 [2. 3. 4. 6. 9.]
 [2. 3. 4. 6. 9.]]


### Feature transformation

In [30]:
from sklearn.preprocessing import FunctionTransformer

features = np.array([[2, 3], [2, 3], [2, 3]])
def add_ten(x: int) -> int:
    return x + 10

ten_transformer = FunctionTransformer(add_ten)
features_ten = ten_transformer.transform(features)
print(features_ten)

[[12 13]
 [12 13]
 [12 13]]


### Outlier detection

In [31]:
from sklearn.covariance import EllipticEnvelope
from sklearn.datasets import make_blobs

features, _ = make_blobs(
    n_samples=10,
    n_features=2,
    centers=1,
    random_state=1)

features[0, 0] = 10000
features[0, 1] = 10000

outlier_detector = EllipticEnvelope(contamination=0.1)
outlier_detector.fit(features)
print(outlier_detector.predict(features))


[-1  1  1  1  1  1  1  1  1  1]


### Feature discretization

In [32]:
from sklearn.preprocessing import Binarizer

age = np.array([
    [6],
    [12],
    [20],
    [36],
    [65]])

binarizer = Binarizer(threshold=18)
age_binarized = binarizer.transform(age)
print(age_binarized)

[[0]
 [0]
 [1]
 [1]
 [1]]


### Grouping observations using clustering

In [37]:
import pandas as pd
from sklearn.datasets import make_blobs
from sklearn.cluster import KMeans

features, _ = make_blobs(
    n_samples=50,
    n_features=2,
    centers=3,
    random_state=1)

dataframe = pd.DataFrame(features, columns=["feature_1", "feature_2"])
clusterer = KMeans(3, random_state=0)
clusterer.fit(features)
dataframe["group"] = clusterer.predict(features)
dataframe.head()

,feature_1,feature_2,group
0,-9.877554,-3.336145,2
1,-7.287210,-8.353986,0
2,-6.943061,-7.023744,0
3,-7.440167,-8.791959,0
4,-6.641388,-8.075888,0
