### Setting up a linear connection

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.datasets import make_regression

# Generate matrix of features
features, target = make_regression(
    n_samples=100,
    n_features=3,
    n_informative=2,
    n_targets = 1,
    noise = 0.2,
    coef = False,
    random_state = 1)

# Create object of linear regression
regression = LinearRegression()

# Fit linear regression model
model = regression.fit(features, target)

# Output the value of the segment
print(model.intercept_)

# Output the values ​​of the feature coefficients
print(model.coef_)

# First value of target vector
print(target[0])

# Predict value
print(model.predict(features)[0])

# Model efficient
print(model.score(features, target))

-0.00965011817881578
[1.95531234e-02 4.42087450e+01 5.81494563e+01]
-20.870747595269407
-20.86192770929682
0.9999901732607787


### Managing Interrelated Coefficients

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.datasets import make_regression
import numpy as np

# Generate matrix of features
features, target = make_regression(
    n_samples=100,
    n_features=2,
    n_informative=2,
    n_targets = 1,
    noise = 0.2,
    coef = False,
    random_state = 1)

# Create an interaction condition
interaction = PolynomialFeatures(degree=3, include_bias=False, interaction_only=True)
features_interaction = interaction.fit_transform(features)

# Create a linear regression object
regression = LinearRegression()

# Construct a linear regression
model = regression.fit(features_interaction, target)

# First value of target vector
print(features[0])

# Multiply the values ​​of the first and second features for each observation
interaction_term = np.multiply(features[:,0], features[:,1])

print(interaction_term[0])

print(features_interaction[0])

[0.0465673  0.80186103]
0.037340501965846186
[0.0465673  0.80186103 0.0373405 ]


### Setting up a nonlinear relationship

In [7]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.datasets import make_regression

# Generate matrix of features
features, target = make_regression(
    n_samples=100,
    n_features=3,
    n_informative=2,
    n_targets=1,
    noise=0.2,
    coef=False,
    random_state=1,
)

# Create polynomial features for x2 and x3
polynomial = PolynomialFeatures(degree=3, include_bias=False)
features_polynomial = polynomial.fit_transform(features)

# Create a linear regression object
regression = LinearRegression()
# Fit the linear regression
model = regression.fit(features_polynomial, target)

# Output the value of the segment
print(features[0])

# Output the value of the first feature squared
print(features[0]**2)

# Output the value of the first feature cubed
print(features_polynomial[0])

[ 0.58591043  0.78477065 -0.95542526]
[0.34329103 0.61586497 0.91283743]
[ 0.58591043  0.78477065 -0.95542526  0.34329103  0.45980531 -0.55979363
  0.61586497 -0.74978971  0.91283743  0.2011378   0.26940473 -0.32798893
  0.36084171 -0.43930961  0.53484097  0.48331276 -0.58841296  0.71636803
 -0.87214794]


### Variance reduction through regularization

In [11]:
from sklearn.linear_model import Ridge
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import make_regression
from sklearn.linear_model import RidgeCV


# Generate matrix of features and target vector
features, target = make_regression(
    n_samples=100,
    n_features=3,
    n_informative=2,
    n_targets=1,
    noise=0.2,
    coef=False,
    random_state=1,
)

# Standardize the features
scaler = StandardScaler()
features_standardized = scaler.fit_transform(features)

# Create a Ridge regression object with alpha=0.5
regression = Ridge(alpha=0.5)

# Fit the Ridge regression
model = regression.fit(features_standardized, target)

# Create a Ridge regression object with cross-validation, specifying the alpha values
regr_cv = RidgeCV(alphas=[0.1, 1.0, 10.0])

# Fit the Ridge regression with cross-validation
model_cv = regr_cv.fit(features_standardized, target)

# Output the coefficients
print(model_cv.coef_)

# Output the best alpha value found through cross-validation
print(model_cv.alpha_)

[1.29223201e-02 4.40972291e+01 5.38979372e+01]
0.1


### Variance reduction via lasso regression

In [ ]:
from sklearn.linear_model import Lasso
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import make_regression

# Generate matrix of features and target vector
features, target = make_regression(
    n_samples=100,
    n_features=3,
    n_informative=2,
    n_targets=1,
    noise=0.2,
    coef=False,
    random_state=1,
)

# Standardize features
scaler = StandardScaler()
features_standardized = scaler.fit_transform(features)

# Create object lasso regression
regression = Lasso(alpha=0.5)

# Adjust regression
model = regression.fit(features_standardized, target)

print(model.coef_)



[-0.         43.58618393 53.39523724]
